<div id="my_uploads">
<p>
<table>
<caption class="caption">Uploaders</caption>
<tr>
<td class="label">Weather Underground:</td>
<td class="data"><a href="https://www.wunderground.com/dashboard/pws/KWAFEDER15">KWAFEDER15</a></td>
</tr>
<tr>
<td class="label">PWS:</td>
<td class="data"><a href="https://www.pwsweather.com/station/pws/kwfeder15">KWFEDER15</a></td>
</tr>
<tr>
<td class="label">CWOP:</td>
<td class="data"><a href="http://www.findu.com/cgi-bin/wxpage.cgi?call=CW6881">CW6881</a></td>
</tr>
<!--
<tr>
<td class="label">AWEKAS:</td>
<td class="data"><a href="https://www.awekas.at/en/instrument.php?id=27345">27345</a></td>
</tr>
-->
<tr>
<td class="label">Windy:</td>
<!--
<td class="data"><a href="https://www.windy.com/station/pws-f0159fce?47.234,-122.361,12">f0159fce</a></td>
-->
<td class="data"><a href="https://www.windy.com/station/madis-C6881?temp,47.310,-122.361,7">MADIS LINK</a></td>
</tr>

</table>
</div>
